// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIQtq_1GhstL5tqWfciSSS7VoVAT8xBg',
    appId: '1:1050766276758:web:9c3114ff00116c74136ab7',
    messagingSenderId: '1050766276758',
    projectId: 'airsky-first-app',
    authDomain: 'airsky-first-app.firebaseapp.com',
    storageBucket: 'airsky-first-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQE0jZ_jHYI91-Nth7tTjy1nM0QTrhqE',
    appId: '1:1050766276758:android:caf677c8ed6386ea136ab7',
    messagingSenderId: '1050766276758',
    projectId: 'airsky-first-app',
    storageBucket: 'airsky-first-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3j0-_-ohtXckVf_E-97s9kj3TCms0iM8',
    appId: '1:1050766276758:ios:e975f5378aa50819136ab7',
    messagingSenderId: '1050766276758',
    projectId: 'airsky-first-app',
    storageBucket: 'airsky-first-app.appspot.com',
    iosClientId: '1050766276758-mk04pbkuogk2dhvkjvrt35q4892jfgub.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
